# Главные сообщения плагина
messages:
  noPermissions: "{prefix}&cУ вас недостаточно прав."
  reloaded: "&6ACore &7» &fПлагин перезагружен!"
  blockCmd: "{prefix}&cДанная команда запрещена в этом мире."
  limits: "{prefix}&fДанная команда на &aсегодня &fзакончилась."
  playerNotFound: "{prefix}&fДанный игрок не найден."
  itemsNotFound: "{prefix}&fДанный кастомный предмет не найден."
  isAdmin: "{prefix}&fВы не можете использовать данную команду."
  cooldown-cmds: "{prefix}Вы отправляете команды слишком часто!"
  cooldown: "{prefix}&cПодождите &a{seconds} &cсекунд."
  iteminhand: "{prefix}&cПредмет должен быть в руке."
  thispageno: "{prefix}&cСтраница не найдена."
  colorHex: "{prefix}&cНекорректный цвет!"

# Команды плагина
commands:
  acore: "&a/acore &f- Команда плагина &6ACore&f."
  abroadcast: "&a/abroadcast &7[&aсообщение&7] &f- Отправить сообщение на весь сервер."
  avanish:
    usage: "&a/avanish &f- Стать невидимым. &7(админский ваниш)"
    on-self: "{prefix}&fВы исчезли. &7(админский ваниш)"
    on-other: "{prefix}&fВы сделали игрока &e{target} &fневидимым."
    off-self: "{prefix}&fВы снова видимы. &7(админский ваниш)"
    off-other: "{prefix}&fВы сделали игрока &e{target} &fснова видимым."
  citems:
    player: "&a/citems &7[&aпредмет&7] &f- Выдать кастомный предмет себе."
    console: "&a/citems &7[&aпредмет&7] &7[&aник&7] &f- Выдать кастомный предмет игроку."
    itemsNotFound: "{prefix}&cПредмет не найден в конфиге."
    itemReceivedSelf: "{prefix}&fВы получили предмет &a{item}&f."
    itemGivenToOther: "{prefix}&fВы выдали игроку &e{target} &fпредмет &a{item}&f."
    itemReceivedFromOther: "{prefix}&fВы получили предмет &a{item} &fот игрока &e{sender}&f."

# Тролл команды
trolls:
  protected: "{prefix}Вы не можете затроллить данного игрока."
  achievementtroll:
    usage: "&a/achievementtroll &7[&aник&7] &7[&aдостижение&7] &f- Выдать игроку фейк-ачивку."
    message: "&f{player} получил достижение «&a[&a{message}&a]&f»"
  lifttroll:
    usage: "&a/lifttroll &7[&aник&7] &7[&aсила&7] &f- Подбросить игрока вверх."
    success: "{prefix}Вы подбросили игрока &e{player} &fс силой &e{power}&f. &b:>"
    invalidNumber: "{prefix}&cИспользуйте число для силы подбрасывания."
    liftedSelf: "{prefix}&cВы не можете подбросить самого себя."
    limitExceeded: "{prefix}&cМаксимальная сила &a{max}"
    # Максимальная сила подкидывания
    maxPower: 10.0
  portaltroll:
    usage: "&a/portaltroll &7[&aник&7] &f- Создать портал из падающих блоков над игроком."
    success: "{prefix}Вы создали портал над игроком &e{player}&f. &b:>"
  bantroll:
    usage: "&a/bantroll &7[&aник&7] &f- Выдать игроку фейк-бан."
    success: "{prefix}Вы забанили игрока &e{player}&f. &b:>"
    reason: "&c&lфейк-бан"
    message:
      - ""
      - "&4Gattino&cLand"
      - ""
      - "&cВы были заблокированы :c"
      - ""
      - "&fКто заблокировал: &a{executor}"
      - "&fДата: &6{date}"
      - "&fПричина: &6{reason}."
      - ""
      - "&cВы были заблокированы навсегда!"
      - ""
      - "&7Разбан покупать на сайте &agattinoland.fun"
      - "&7Подать жалобу - &c/report"
      - ""

# Настройка плагина
settings:
  # Частицы для лобби/спавна
  particles:
    cherry:
      world: "world"
      enabled: false
      coordinates:
        x: -14.5
        y: 100.0
        z: 15.5
      counts: 10
      deltaX: 5.0
      deltaY: 5.0
      deltaZ: 5.0
      speed: 0.0
      particle: "CHERRY_LEAVES"

  # Настройка плит для прыжка
  jump-plate:
    enabled: false
    block: "LIGHT_WEIGHTED_PRESSURE_PLATE"
    knockback:
      power: 3.0 # Сила отбрасывания
      powerY: 0.9 # Отбрасывание по координате Y

  # Ограничение спавна сущностей
  spawnLimit:
    enabled: true
    mobs: 10 # Количество одного вида мобов
    stands: 32 # Количество стоек для брони
    minecarts: 10 # Количество вагонеток
    boats: 10 # Количество лодок
    radius: 64 # Радиус в котором можно спавнить сущности
    message: "{prefix}Игрок &e{player} &fпревысил лимит сущностей. &7({max} шт.)"

events:
  PlayerJoin:
    title:
      enabled: true
      firstJoin:
        line1: "%acore_title%"
        line2: "&fПриятной игры &a☺"

        # Время в тиках
        fade-in-time: 10 # Время появления
        stay-time: 70 # Время задержки перед исчезновением
        fade-out-time: 20 # Время исчезновения

      join:
        line1: "%acore_title%"
        line2: "&fПриятной игры &a☺"

        # Время в тиках
        fade-in-time: 10 # Время появления
        stay-time: 70 # Время задержки перед исчезновением
        fade-out-time: 20 # Время исчезновения

  # Выполнение команд при падении в пропасть
  VoidCmds:
    enabled: true
    # Ниже какой высоты должен находится игрок, чтобы сработала команда
    height: 0
    # Задержка между выполнением команд в списке, срабатает первая команда через delay секунд вторая
    delay: 1
    worlds:
      - hub
    commands:
      - rt {player} world
      - heal {player}

  # Выполнение команд в защищенных регионах от игроков/донатеров
  # Нужно если вы хотите защитить регион своего админ домика .-.
  PlayerMove:
    protectedRegions:
      enabled: true
      # Какие регионы требуется защитить
      regions:
        - akv5
      # Любая команда чтобы выгнать игрока с региона
      commands:
        - spawn {player}

  # Вокруг пвп-арены появляется стекло, как барьер во время пвп между игроками
  PvPArena:
    border: false
    region: pvp


# Админы на которых не действуют некоторые функции плагина
# Команды, которые не действуют на админов (нельзя запретить любые телепортации от CMI)
# Блокировка команд в определенном мире

# Добавить админа по нику
admins:
  - akv5

# Добавить админа по айпи
adminIps: []

# Блокировка команд, которые нельзя выполнять на админов из списка
blockedCmds:
  - dupeip

# Блокировка команд в мирах
blockCmds:
  enabled: true
  first_worlds:
    - hub
    - spawn
  second_worlds:
    - hub
    - spawn
    - world
    - world_the_end
    - world_nether
  first_commands:
    - /cmi jump
    - /cmi time
    - /cmi shoot
    - /day
    - /night
  second_commands:
    - /rg info akv5
    - /rg i akv5
    - /region info akv5
    - /region i akv5
    - /regions info akv5
    - /regions i akv5

block:
  # Блокировка символов в чате
  SymbolChat:
    enabled: true
    # Блокировка символов/слов в чате
    symbols:
      - "^.*[ａ-ｚＡ-Ｚ]+.*$"
      - "^.*[Ⓐ-Ⓩ]+.*$"
      - "^.*[ⓐ-ⓩ]+.*$"
      - "^.*[ᴀ-ᴢ]+.*$"
      - "&k"
      - "& k"
    notify: "{prefix}&e{player} &fнаписал запрещенные символы: &c{message}&f."
    message: "{prefix}&cДанный символ запрещён!"

  # Блокировка символов в командах
  SymbolCommands:
    enabled: true
    commands:
      - "/prefix"
      - "/зкуашч"
      - "/cmi titlemsg"
    symbols:
      - "&k"
      - "& k"
    # Блокировка слов в командах, рекомендуется использовать регулярные символы regex
    # иначе вы будете блокировать каждое слово отдельно любыми символами
    blockedWords: []

    # Блокировка символов/слов в командах
    blockedRegex:
      - "^.*[ａ-ｚＡ-Ｚ]+.*$"
      - "^.*[Ⓐ-Ⓩ]+.*$"
      - "^.*[ⓐ-ⓩ]+.*$"
      - "^.*[ᴀ-ᴢ]+.*$"
    notify: "{prefix}&e{player} &fнаписал запрещенные символы: &c{message}&f."
    message: "{prefix}&cДанный символ запрещён!"

# Уведомлять об выполненных командах
notify:
  enabled: false
  commands:
    - "/prefix"
    - "/зкуашч"
  message: "{prefix}&e{player} &fнаписал: &c{message}&f."

# Автоматическая загрузка текстур при входе
# Команда для обновления текстур /rp, после выполнения надо перезайти
textures:
  enabled: false
  url: "Здесь прямая ссылка на скачивание текстур пака"
  message: "{prefix}Набор ресурсов был обновлён, перезайдите!"